version: "3"
services:
    jenkins:
        image: pyjenkins
        container_name: "jenkins_how"
        ports:
          - "8000:8080"
          - "50000:50000"
        volumes:
          - "./jenkins_home:/var/jemkins_home"
          - "./cambio:/cambio" 